// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"blog-backend/app/dao/internal"
	"blog-backend/app/dao/utils"
)

// articleDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type articleDao struct {
	*internal.ArticleDao
}

var (
	// Article is globally public accessible object for table article operations.
	Article articleDao
	// UUID generator for table 'article'
	ariticleWorker *utils.TableWorker
)

func init() {
	Article = articleDao{
		internal.NewArticleDao(),
	}
	ariticleWorker = utils.NewTableWorker(Article.Table)
}
