// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"blog-backend/app/dao/internal"
)

// articleCategoryDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type articleCategoryDao struct {
	*internal.ArticleCategoryDao
}

var (
	// ArticleCategory is globally public accessible object for table article_category operations.
	ArticleCategory articleCategoryDao
)

func init() {
	ArticleCategory = articleCategoryDao{
		internal.NewArticleCategoryDao(),
	}
}

// Fill with you ideas below.
