// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"blog-backend/app/dao/internal"
)

// articleExtDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type articleExtDao struct {
	*internal.ArticleExtDao
}

var (
	// ArticleExt is globally public accessible object for table article_ext operations.
	ArticleExt articleExtDao
)

func init() {
	ArticleExt = articleExtDao{
		internal.NewArticleExtDao(),
	}
}

// Fill with you ideas below.
