// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"blog-backend/app/dao/internal"
)

// tagArticleMappingDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type tagArticleMappingDao struct {
	*internal.TagArticleMappingDao
}

var (
	// TagArticleMapping is globally public accessible object for table tag_article_mapping operations.
	TagArticleMapping tagArticleMappingDao
)

func init() {
	TagArticleMapping = tagArticleMappingDao{
		internal.NewTagArticleMappingDao(),
	}
}

// Fill with you ideas below.
