// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"blog-backend/app/dao/internal"
)

// userArticleMappingDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type userArticleMappingDao struct {
	*internal.UserArticleMappingDao
}

var (
	// UserArticleMapping is globally public accessible object for table user_article_mapping operations.
	UserArticleMapping userArticleMappingDao
)

func init() {
	UserArticleMapping = userArticleMappingDao{
		internal.NewUserArticleMappingDao(),
	}
}

// Fill with you ideas below.
