// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"blog-backend/app/dao/internal"
)

// userProfileDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type userProfileDao struct {
	*internal.UserProfileDao
}

var (
	// UserProfile is globally public accessible object for table user_profile operations.
	UserProfile userProfileDao
)

func init() {
	UserProfile = userProfileDao{
		internal.NewUserProfileDao(),
	}
}

// Fill with you ideas below.
